name: 'Contribution'

permissions:
  contents: read

on:
  push:

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  test:
    name: 'Test'
    uses: ./.github/workflows/test.yml
    needs:
      - build
  deploy:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    if: github.actor != 'dependabot[bot]'
    needs:
      - test
