name: 'Deploy'

on:
  workflow_call:

jobs:
  deploy:
    name: 'Templates'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout (GH Pages)'
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
      - name: 'Clean up'
        run: |
          rm -rf "./${GITHUB_REF_NAME}"
        shell: bash
      - name: 'Download build artifact'
        uses: actions/download-artifact@v4
        with:
          name: templates
          path: "./${GITHUB_REF_NAME}"
      - name: 'Deploy'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m "Automated deployment to GitHub Pages (${GITHUB_REF_NAME}): ${GITHUB_SHA}" --allow-empty
          git push origin gh-pages --force
        shell: bash
