name: 'OSS Review Toolkit'

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 1 * *" # at 00:00 on day-of-month 1
  workflow_dispatch: # enables manual run, - before manual run is triggered ensure step "Send ORT Analyzer Result to OSO" is disabled / commented out

jobs:
  ort:
    name: 'ORT'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        uses: ./.github/actions/install
      - name: "Login"
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.OSO_AWS_ECR_REGISTRY }}
          username: ${{ secrets.OSO_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.OSO_AWS_SECRET_ACCESS_KEY }}
      - name: "Analyze"
        run: |
          docker run --user root -v "$PWD":/project ${{ vars.OSO_AWS_ECR_REGISTRY }}/ort:latest analyze -i /project -o /project/ort
        shell: bash
      - name: "Report"
        run: |
          docker run --user root -v "$PWD":/project ${{ vars.OSO_AWS_ECR_REGISTRY }}/ort:latest report -i /project/ort/analyzer-result.yml -o /project/ort -f StaticHtml
        shell: bash
      - name: 'Upload'
        uses: actions/upload-artifact@v4
        with:
          name: ort-analysis
          path: ./ort
