name: 'Pull request'

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  # test:
  #   name: 'Test'
  #   uses: ./.github/workflows/test.yml
  #   needs:
  #     - build
  deploy:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs:
      - build
