name: 'Test'

on:
  workflow_call:

jobs:
  e2e:
    name: 'E2E'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download'
        uses: actions/download-artifact@v5
        with:
          name: templates
          path: ./dist
      - name: 'E2E'
        run: npm run test:e2e
        shell: bash
  a11y:
    name: 'A11y'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download'
        uses: actions/download-artifact@v5
        with:
          name: templates
          path: ./dist
      - name: 'A11y'
        run: npm run test:a11y
        shell: bash
  vrt:
    name: 'VRT'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [ 1, 2, 3 ]
        shardTotal: [ 3 ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download'
        uses: actions/download-artifact@v5
        with:
          name: templates
          path: ./dist
      - name: 'VRT'
        run: npm run test:vrt -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        shell: bash
      - name: 'VRT Regression'
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vrt-regression-${{ matrix.shardIndex }}
          path: ./tests/vrt/test-results
  lh:
    name: 'LH'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [ 1, 2, 3, 4 ]
        shardTotal: [ 4 ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download'
        uses: actions/download-artifact@v5
        with:
          name: templates
          path: ./dist
      - name: 'LH'
        run: npm run test:lh -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        shell: bash
      - name: 'LH Regression'
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lh-regression-${{ matrix.shardIndex }}
          path: ./tests/lh/test-results
